@startuml

class UNPCAnimInstance {
    + UNPCAnimInstance()
    + NativeInitializeAnimation() : void
    + NativeUpdateAnimation(DeltaSeconds: float) : void
    - Owner : ACharacter*
    - Movement : UCharacterMovementComponent*
    - Velocity : FVector
    - GroundSpeed : float
    - bIsIdle : uint8
    - MovingThreshould : float
}

@enduml
